### ISSUE TITLE
HTTP status 403 Forbidden: User quota exceeded

### ISSUE THREAD

**Issue by ibaris** [sentinelsat/sentinelsat#493]
The `download_all` module causes the following error message:

```python
Fetching archival status:  17%|█▋        | 4/24 [00:05<00:27,  1.36s/ products]User quota exceeded: MediaRegulationException : An exception occured while creating a stream: Maximum number of 4 concurrent flows achieved by the user "xxx"
Fetching archival status:  17%|█▋        | 4/24 [00:06<00:34,  1.72s/ products]
Traceback (most recent call last):
  File "C:\Users\xxx\miniforge3\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-35ca78a4b9cf>", line 1, in <module>
    __api.download_all(product_ids, directory_path=dest_path, n_concurrent_dl=1)
  File "C:\Users\xxx\miniforge3\lib\site-packages\sentinelsat\sentinel.py", line 723, in download_all
    is_online = not self.trigger_offline_retrieval(pid)
  File "C:\Users\xxx\miniforge3\lib\site-packages\sentinelsat\sentinel.py", line 636, in trigger_offline_retrieval
    raise LTAError(msg, r)
sentinelsat.exceptions.LTAError: HTTP status 403 Forbidden: User quota exceeded: MediaRegulationException : An exception occured while creating a stream: Maximum number of 4 concurrent flows achieved by the user "xxx"
```

Even if I try to set the parameter `n_concurrent_dl` to `1`, the result is the same. However, I am able to download every single product with a loop and by using  the `download` function:

```python
for item in products.keys():
    api.download(item, "")
```

Why I wanted to use the `download_all ` function is, I would like to download conveniently products from the LTA, as you described [here](https://sentinelsat.readthedocs.io/en/master/api_overview.html#lta-products). 

Are there a workaround for this issue? I saw the merge request  #491. But even with this code the `download_all` function does not work for me.

**Comment by z4zz** [comment]
the main reason is that online status is now checked by triggering function 
you have 2 options:
1. modify `download_all` (line **723**): `is_online = not self.trigger_offline_retrieval(pid)` to `is_online = self.is_online(pid)`
2. modify `trigger_offline_retrieval` (line **636**): `raise LTAError(msg, r)` to `return False`

**Comment by ibaris** [comment]
Sorry for my late reply. I have not received any notification. Thank you for your reply and quick fix.  Now I get a bunch of endless errors where in between downloads seem to start, but it aborts after 2 or 3 downloads:
```
  File "C:\Users\xxx\miniforge3\lib\site-packages\sentinelsat\sentinel.py", line 891, in _download_online_retry
    return self.download(id, directory_path, checksum, **kwargs)
  File "C:\Users\xxx\miniforge3\lib\site-packages\sentinelsat\sentinel.py", line 527, in download
    self._download_outer(product_info, path, checksum)
  File "C:\Users\xxx\miniforge3\lib\site-packages\sentinelsat\sentinel.py", line 565, in _download_outer
    product_info["downloaded_bytes"] = self._download(
  File "C:\Users\xxx\miniforge3\lib\site-packages\sentinelsat\sentinel.py", line 1197, in _download
    _check_scihub_response(r, test_json=False)
  File "C:\Users\xxx\miniforge3\lib\site-packages\sentinelsat\sentinel.py", line 1480, in _check_scihub_response
    raise ServerError(msg, response)
sentinelsat.exceptions.ServerError: HTTP status 403 Forbidden: MediaRegulationException : An exception occured while creating a stream: Maximum number of 4 concurrent flows achieved by the user "xxx"
User quota exceeded: MediaRegulationException : An exception occured while creating a stream: Maximum number of 4 concurrent flows achieved by the user "xxx"
User quota exceeded: MediaRegulationException : An exception occured while creating a stream: Maximum number of 4 concurrent flows achieved by the user "xxx"
User quota exceeded: MediaRegulationException : An exception occured while creating a stream: Maximum number of 4 concurrent flows achieved by the user "xxx"
User quota exceeded: MediaRegulationException : An exception occured while creating a stream: Maximum number of 4 concurrent flows achieved by the user "xxx"
User quota exceeded: MediaRegulationException : An exception occured while creating a stream: Maximum number of 4 concurrent flows achieved by the user "xxx"
User quota exceeded: MediaRegulationException : An exception occured while creating a stream: Maximum number of 4 concurrent flows achieved by the user "xxx"

```
The downloads here are not from the LTA by the way. There are data from this year. Moreover, I get an error because the function `to_geojson` tries to parse a "NaT" object to a datetime, which does not work. But I will open a new issue for that

**Comment by ibaris** [comment]
Even if the single `download` function I get errors like this:

```python
    raise LTATriggered(id)
sentinelsat.exceptions.LTATriggered: Product b18aacca-85d6-4e19-b3c1-7dd509076ed0 is not online. Triggered retrieval from the Long Term Archive.
```

The scene I try to download is from the date: 26.03.2021

**Comment by BenMueller** [comment]
Having the same issue as in the initial post- even after creating brand new accounts, I get the `User quota exceeded` no matter what I do (even with downloading a single --uuid). However, using the [SentinelDataHub](https://github.com/SentinelDataHub/Scripts) scripts seems to work, so it isn't on their end.

Trying #491 does not work for me either. Let me know if y'all have any questions/debugging you want me to do! Thanks

**Comment by avalentino** [comment]
@BenMueller you may wand to give try to my (hot fixes branch)[https://github.com/avalentino/sentinelsat/tree/hotfixes).
If it works fine for you I will try to make a proper PR ASAP.

**Comment by ibaris** [comment]
It seems that there is something wrong with Scihub. Because almost 30% of my downloaded LTA products are corrupted. I already contacted ESA. Thank you very much. I will try the branch :)

**Comment by avalentino** [comment]
> It seems that there is something wrong with Scihub. Because almost 30% of my downloaded LTA products are corrupted.

@ibaris yes, there is an issue on the SciHub side unfortunately (see https://scihub.copernicus.eu/news/News00893).
Please keep us posted if you have news form them.

**Comment by fpl** [comment]
I'm currently finding at least three different flaws due to issues with the current release of dhus. 
One is the wrong checksum for some products (not LTA) which seems reported in the News issue, another is the the mysterious
error 500:
```
HTTP status 500 Internal Server Error: UnsupportedOperationException : Error creating stream from file                                                                   
/mnt/s2bl2a/dhus/incoming/x6/x6/x8/S2B_MSIL2A_20210605T110619_N0300_R137_T30TUN_20210605T143100.zip 
```
But this one seems not related, I will have a try tomorrow with your hotfix, thanks Antonio.

**Comment by fpl** [comment]
Ok, it seems fixing the reported issue about:
```
User quota exceeded: MediaRegulationException : An exception occured while creating a stream: Maximum number of 4 concurrent flows achieved by the user "xxx"
```
at least here, tested on Debian sid.

**Comment by avalentino** [comment]
Thanks Francesco got the review.
I will try to cleanup the code and open a PR ASAP.
Unfortunately the PR #491 (on top of which my patch is base) is still not merged and seems to have problems with tests.

**Comment by ka-nishadh** [comment]
Was facing similar issue with error of 
```<class 'sentinelsat.sentinel.SentinelAPIError'> HTTP status 500 Internal Server Error: MediaRegulationException : An exception occured while creating a stream: Maximum number of 40 concurrent flows achieved by the user 'xxx'```

But there was no concurrent flows is enabled or doing the download for less than 5-10 images. However this error is being not raised for newer accounts.

**Comment by j08lue** [comment]
> this error is being not raised for newer accounts.

Are you sure about this part, @ka-nishadh? This gets weirder and weirder...

**Comment by BenMueller** [comment]
@avalentino Trying the hotfix branch linked above still gives me the `Maximum number of 4 concurrent flows achieved` error.

Per the comment by @ka-nishadh , I've noticed some seemingly similarly odd behavior in the past but testing just now a brand-new account gives the same error I mentioned above. So YMMV.

> This gets weirder and weirder...

Yes.

**Comment by ka-nishadh** [comment]
Yes, can be tested with making a new account in eumetsat coda, https://coda.eumetsat.int/#/home. Used sentinelsat version 0.13. 
```
from sentinelsat.sentinel import SentinelAPI

api = SentinelAPI('username', 'password', 'https://coda.eumetsat.int')

download_keys=['5b31aa1a-859a-490f-a78b-eea436d7f8d3', '353c6000-3d21-4fc5-841a-e4467d3a31be']

api.download_all(download_keys,directory_path='/home/',max_attempts=4,checksum=True)
```

**Comment by fpl** [comment]
> @avalentino Trying the hotfix branch linked above still gives me the `Maximum number of 4 concurrent flows achieved` error.
> 

That's weird, I'm currently using the @avalentino hotfix branch and it does not fail, with both old and new accounts. It fails for many other reasons, but they are all problems on the server side.

**Comment by avalentino** [comment]
The entire situation is very very strange. I have just experimented the same `Maximum number of 4 concurrent flows achieved` errors just trying to download a single product form the SciHub web UI (but I had previously attempted to download something via sentinelsat).

I can't understand if it is an incorrect error message i.e. the problem is actually something different, or if these is some kind of automatic locking mechanism that blocks users for some time in certain conditions.

In any case it seems to be very very hard to get dat form the SciHub in this period.

I have sent another support request to the Copernicus EO Support, bu please if someone has a solution or a workaround please share.

**Comment by ka-nishadh** [comment]
There is this AWS open data for sentinel data, for sentinel 3, https://registry.opendata.aws/sentinel-3/ and for sentinel 2, https://registry.opendata.aws/sentinel-2/

Currently the old/new account issue is resolved and downloading is working without issue for EUMETSAT sentinel3 data source. 
However, there were data disruption in AWS open data fro sentinel 3 as well during the issue period (from June 24).

**Comment by fpl** [comment]
> The entire situation is very very strange. I have just experimented the same `Maximum number of 4 concurrent flows achieved` errors just trying to download a single product form the SciHub web UI (but I had previously attempted to download something via sentinelsat).
> 
> I can't understand if it is an incorrect error message i.e. the problem is actually something different, or if these is some kind of automatic locking mechanism that blocks users for some time in certain conditions.
> 
> In any case it seems to be very very hard to get dat form the SciHub in this period.
> 
> I have sent another support request to the Copernicus EO Support, bu please if someone has a solution or a workaround please share.

Indeed, that error still appears from time to time here at least for S2 images. I will try to follow the history of the incriminated products, because I suspect that it is an issue of LTA and another type of internal server error...

**Comment by avalentino** [comment]
@fpl in my case products where all online.
There was indeed a problem with restoration form LTA but on SciHub they clam they have fixed it [1].
Some user also confirmed that the issue with LTA seems to be fixed #501 but the situation is not clear for me.

[1] https://scihub.copernicus.eu/news/News00893

**Comment by avalentino** [comment]
@ka-nishadh unfortunately was do not helps in my case because I need S1 SLC product.

**Comment by ka-nishadh** [comment]
May check this, https://registry.opendata.aws/sentinel-1/

**Comment by avalentino** [comment]
> May check this, https://registry.opendata.aws/sentinel-1/

yes, I have looked at it but, unfortunately, it seems to include only GRD products (in need SLC).
thanks again

**Comment by ibaris** [comment]
I received a response today:
```
Dear Ismail,

With reference to your below request,
please be informed that this was a known issue. It was noted that occasionally products were restored with a smaller size with respect to the expected one, resulting in a corrupted zip file when attempting its decompression, even if the original products stored are consistent in size.  

We would like to inform you that this issue has been solved on 1st July as per news published on the Copernicus Open Access Hub website at https://scihub.copernicus.eu/news/News00898. 

Considering the above please note that: 

if you have performed the LTA retrieval before the 1st July we would kindly invite you to re-try to retrieve again the needed products  
if you have performed the LTA retrieval after the 1st July please let us know as we can check the corrupted image/s with the technical team 
       
We apologise for the inconvenience this might cause to your activity. 

Thank you in advance for your feedback. 

Kind Regards,   


Helene
SCI Team
Copernicus Services Coordinated Interface ESA service operated by Serco
Mail: EOSupport@copernicus.esa.int
Portal: https://Spacedata.Copernicus.eu/
```

**Comment by avalentino** [comment]
@ibaris yes, this is another piece of the puzzle
I think anyway that you case is more related to #501

**Comment by valgur** [comment]
This problem should now be probably fixed by #508. Will create a new release soon.
